"""MongoDB adapter — executes read-only MongoDB queries via PyMongo."""

from __future__ import annotations

import json
import logging
from typing import Any
from urllib.parse import urlparse

from pymongo import MongoClient

from app.services.adapters.base import BaseAdapter

logger = logging.getLogger(__name__)

# Operations that modify data — we reject them.
_WRITE_OPS = {"insert", "update", "delete", "drop", "rename", "create"}


class MongoDBAdapter(BaseAdapter):
    """Execute MongoDB find/aggregate queries in read-only mode."""

    def __init__(self, db_url: str) -> None:
        self._client: MongoClient = MongoClient(db_url)
        # Extract the database name from the connection URL
        parsed = urlparse(db_url)
        self._db_name: str = parsed.path.lstrip("/").split("?")[0] or "test"

    @property
    def _db(self):  # noqa: ANN202
        return self._client[self._db_name]

    # ── public API ───────────────────────────────────────────────────────

    def execute(self, query: str) -> list[dict[str, Any]]:
        """Execute a JSON-encoded MongoDB query.

        Expected format (generated by the LLM)::

            {
                "collection": "contacts",
                "operation": "find",          // "find" or "aggregate"
                "filter": {"score": {"$gt": 5}},   // for find
                "pipeline": [...],             // for aggregate
                "projection": {"_id": 0},     // optional
                "limit": 100                  // optional, default 100
            }
        """
        try:
            spec = json.loads(query)
        except json.JSONDecodeError as exc:
            raise ValueError(f"MongoDB query must be valid JSON: {exc}") from exc

        collection_name = spec.get("collection")
        operation = spec.get("operation", "find").lower()

        if not collection_name:
            raise ValueError("MongoDB query must specify a 'collection'.")
        if operation in _WRITE_OPS:
            raise PermissionError(
                f"Write operation '{operation}' is not allowed. Read-only access only."
            )

        collection = self._db[collection_name]
        limit = int(spec.get("limit", 100))

        if operation == "find":
            filter_doc = spec.get("filter", {})
            projection = spec.get("projection")
            cursor = collection.find(filter_doc, projection).limit(limit)
            results = []
            for doc in cursor:
                doc["_id"] = str(doc["_id"])  # ObjectId → str
                results.append(doc)
            logger.info("MongoDB find on %s returned %d docs", collection_name, len(results))
            return results

        if operation == "aggregate":
            pipeline = spec.get("pipeline", [])
            cursor = collection.aggregate(pipeline)
            results = []
            for doc in cursor:
                if "_id" in doc:
                    doc["_id"] = str(doc["_id"])
                results.append(doc)
            logger.info("MongoDB aggregate on %s returned %d docs", collection_name, len(results))
            return results

        raise ValueError(f"Unsupported MongoDB operation: '{operation}'")

    def close(self) -> None:
        self._client.close()
        logger.debug("MongoDB client closed")
